// src/components/sostenibilidad.js

export const sostenibilidadQuestions = [
  { q: "¿Cuáles son los tres pilares del desarrollo sostenible?", opts: ["Tecnología, rentabilidad y ecología", "Medioambiental, económico y social", "Humano, tecnológico y regulatorio", "Ambiental, digital y financiero"], ans: 1 },
  { q: "El sistema biológico formado por una comunidad de seres vivos que habita un medio físico se denomina:", opts: ["Sistema humano", "Ecosistema", "Sociedad", "Equilibrio"], ans: 1 },
  { q: "Los recursos naturales:", opts: ["Proporcionan materiales a los sistemas económicos", "Son materiales que se extraen de la naturaleza y se utilizan en la producción", "Son materiales que proceden de la actividad humana y resultan inservibles si no se transforman", "Son dinero, fundamentalmente"], ans: 1 },
  { q: "No es una dimensión del desarrollo sostenible:", opts: ["La económica", "La social", "La estética", "La ecológica"], ans: 2 },
  { q: "Para que los ecosistemas sean sostenibles, nuestra huella ecológica debe ser:", opts: ["Igual que la biocapacidad", "Mayor que la biocapacidad", "Menor que la biocapacidad", "No influye en el desarrollo sostenible"], ans: 2 },
  { q: "El cambio climático actual tiene su principal origen en:", opts: ["La actividad económica", "La capa de ozono", "La actividad del Sol", "La contaminación del suelo"], ans: 0 },
  { q: "El mayor efecto medioambiental de la contaminación atmosférica es:", opts: ["El efecto invernadero", "Las formas de producir que despilfarran recursos", "La pérdida de biodiversidad", "La contaminación del suelo"], ans: 0 },
  { q: "El cambio climático supone para las empresas:", opts: ["Menor demanda de energía en los hogares", "Una mayor productividad de su plantilla", "El aumento de las primas de sus seguros", "Un aumento en sus ingresos"], ans: 2 },
  { q: "Plantar bosques es una medida de:", opts: ["Descarbonización", "Desmaterialización", "Desertización", "Adaptación"], ans: 0 },
  { q: "Las medidas de mitigación buscan:", opts: ["Adaptar la empresa a la nueva situación climática", "Frenar o atenuar el cambio climático", "Atender a las personas con problemas de salud", "Reducir la actividad económica"], ans: 1 },
  { q: "No es una dimensión como tal de los ODS:", opts: ["La cultural", "La económica", "La social", "La ecológica"], ans: 0 },
  { q: "Los ODS son objetivos de obligado cumplimiento por:", opts: ["Las personas físicas únicamente", "Las empresas privadas solamente", "La ONU exclusivamente", "Las administraciones públicas"], ans: 3 },
  { q: "¿Cuál es la función de los indicadores de desempeño?", opts: ["Informar de la rentabilidad", "Medir el grado de consecución de las metas del desarrollo sostenible", "Especificar situaciones de llegada", "Coordinar acciones de la humanidad"], ans: 1 },
  { q: "No es un ámbito del consumo responsable:", opts: ["El transporte", "Los bienes duraderos", "El agua", "La producción"], ans: 3 },
  { q: "Desplazarse a pie ayuda especialmente a cumplir el ODS:", opts: ["8. Trabajo decente", "11. Ciudades y comunidades sostenibles", "12. Producción y consumo responsables", "15. Vida terrestre"], ans: 1 },
  { q: "Un empleado sin responsabilidades directivas puede ayudar a los ODS:", opts: ["No puede hacer nada", "Esperando órdenes", "Haciendo lo mismo que otros", "Aplicando principios de consumo responsable en su puesto"], ans: 3 },
  { q: "Para integrar los ODS en la estrategia empresarial es recomendable implicarse en:", opts: ["Un ODS concreto", "Una meta concreta", "Un indicador concreto", "Todos los ODS a la vez"], ans: 1 },
  { q: "¿Qué iniciativa de la UE busca lograr la neutralidad de carbono?", opts: ["El Pacto Verde Europeo", "Estrategia de Movilidad Sostenible", "Nueva Estrategia Industrial", "Todas las anteriores"], ans: 3 },
  { q: "No es una iniciativa surgida en la UE:", opts: ["El Pacto Verde Europeo", "Nueva Estrategia Industrial", "El acuerdo de París", "Estrategia de Movilidad Sostenible"], ans: 2 },
  { q: "Las iniciativas de la UE para los ODS suponen ventajas como:", opts: ["Mayor riesgo de sanciones", "Reducción de impuestos", "Normas más estrictas", "Ayudas para mejorar la resiliencia"], ans: 3 },
  { q: "La Agenda 2030:", opts: ["Es única para la ONU", "Es adaptada por administraciones para sus estrategias", "Se creó en España", "Busca neutralidad para 2030"], ans: 1 },
  { q: "La mayor parte del empleo lo generan:", opts: ["Entidades del tercer sector", "La banca", "Las administraciones", "Las empresas"], ans: 3 },
  { q: "Sobre los grupos de interés, señala la afirmación falsa:", opts: ["Son colectivos humanos", "Influyen en las decisiones", "Las decisiones los influyen", "Siempre son externos a la empresa"], ans: 3 },
  { q: "Es un grupo de interés interno:", opts: ["Los proveedores", "La competencia", "Los clientes", "Los propietarios"], ans: 3 },
  { q: "El grupo de interés que busca mejor producto al menor precio son:", opts: ["Los propietarios", "Los directivos", "Los clientes", "Los proveedores"], ans: 2 },
  { q: "Los criterios ASG sirven para:", opts: ["Aumentar beneficios exclusivamente", "Evaluar prácticas y guiar decisiones sostenibles", "Sustituir la dirección", "Exigir auditoría interna"], ans: 1 },
  { q: "Los aspectos ASG relacionados con el trato a las personas son:", opts: ["Ambientales", "Sociales", "Financieros", "De gobernanza"], ans: 1 },
  { q: "Los aspectos ASG relacionados con la ética empresarial son:", opts: ["Ambientales", "Sociales", "De gobernanza", "Filosóficos"], ans: 2 },
  { q: "Dentro de la 'A' de los ASG se incluye:", opts: ["Derechos humanos", "Gobernanza corporativa", "Mitigación del cambio climático", "Rotación del personal"], ans: 2 },
  { q: "No es un aspecto ASG ambiental:", opts: ["Adaptación climática", "Biodiversidad", "Economía circular", "Relación con comunidades"], ans: 3 },
  { q: "Un riesgo de no aplicar criterios sociales es:", opts: ["Reducción del transporte", "Absentismo y dificultad para atraer talento", "Más innovación", "Exceso de stock"], ans: 1 },
  { q: "Una buena gestión ASG permite:", opts: ["Disminuir motivación", "Perder financiación", "Mejorar reputación y atraer talento", "Reducir transparencia"], ans: 2 },
  { q: "Un estado no financiero organiza sus indicadores según:", opts: ["Grupos de interés", "Los ODS", "Los aspectos ASG", "Líneas de negocio"], ans: 2 },
  { q: "Las normas NEIS han sido creadas por:", opts: ["La Unión Europea", "El Gobierno de España", "Naciones Unidas", "Consejería de Medio Ambiente"], ans: 0 },
  { q: "La integración de aspectos ASG supone para la empresa:", opts: ["Peor acceso a financiación", "Mejor imagen de marca", "Peor retención de talento", "Menor beneficio a la larga"], ans: 1 },
  { q: "Las empresas redactan Informes No Financieros por exigencia de:", opts: ["La OTAN", "La Unión Europea", "El Banco Mundial", "La OMS"], ans: 1 },
  { q: "La verificación externa de informes de sostenibilidad por auditoría:", opts: ["Es opcional", "Está prohibida", "Es obligatoria", "Solo aplica a ONG"], ans: 2 },
  { q: "¿Qué riesgo asume una empresa que ignora los criterios ASG?", opts: ["Sanciones y pérdida de confianza", "Mejor competitividad", "Anticipar riesgos", "Incrementar resiliencia"], ans: 0 },
  { q: "La economía lineal se caracteriza por:", opts: ["Priorizar el reciclaje", "Extraer-fabricar-consumir-desechar", "Uso de renovables", "Minimizar residuos"], ans: 1 },
  { q: "Ventaja clave de la economía circular:", opts: ["Más residuos", "Mayor velocidad de producción", "Dependencia de fósiles", "Reduce necesidad de materias primas vírgenes"], ans: 3 },
  { q: "Beneficio ambiental directo de la economía circular:", opts: ["Más contaminación", "Disminución de residuos al mantener materiales en uso", "Más vertidos", "Extracción continua"], ans: 1 },
  { q: "La economía circular busca:", opts: ["Limitar proveedores", "Mantener el valor de recursos el mayor tiempo posible", "Más desechables", "Acortar el ciclo de vida"], ans: 1 },
  { q: "'Renovar' en las 7R significa:", opts: ["Crear productos nuevos", "Dar nuevo uso a productos existentes", "Consumir más recursos", "Transformar desechos"], ans: 1 },
  { q: "Con las 7R, el valor de los productos en su ciclo de vida:", opts: ["Aumenta rápidamente", "No se ve afectado", "Se mantiene por más tiempo", "Se reduce rápidamente"], ans: 2 },
  { q: "Dos procesos asociados a la economía circular son:", opts: ["Deslocalización y externalización", "Desmaterialización y descarbonización", "Descentralización y concentración", "Deforestación y desertización"], ans: 1 },
  { q: "Fase del ciclo de vida donde el producto llega al consumidor:", opts: ["Consumo", "Desecho", "Producción", "Distribución"], ans: 0 },
  { q: "En el modelo lineal, cada fase se relaciona directamente:", opts: ["Solo con la anterior", "Con todas a la vez", "Con todas las de atrás", "Con la anterior y la posterior"], ans: 3 },
  { q: "Usar recursos no renovables expone al riesgo de:", opts: ["Contaminación", "Inseguridad laboral", "Escasez y precios mayores", "Menor expansión"], ans: 2 },
  { q: "El ciclo de vida comienza con:", opts: ["Distribución", "Consumo", "Aprovisionamiento", "Desecho"], ans: 2 },
  { q: "El ecodiseño busca:", opts: ["Producción respetuosa", "Integración de aspectos ambientales en el diseño", "Aspectos económicos en diseño", "Aspectos ambientales en consumo"], ans: 1 },
  { q: "El ecodiseño según ISO 14006 se enfoca en:", opts: ["Reducir coste de marketing", "Minimizar impacto ambiental del ciclo de vida", "Aumentar rotación", "Vender premium"], ans: 1 },
  { q: "Un principio del ecodiseño es:", opts: ["Mayor emisión", "Facilitar reparabilidad", "Aumentar consumo energético", "Aumentar residuos"], ans: 1 },
  { q: "Producto mal diseñado desde el ecodiseño:", opts: ["Envase compostable", "Reduce consumo", "Materiales difíciles de separar", "Alta durabilidad"], ans: 2 },
  { q: "Todo proceso de ecodiseño comienza por:", opts: ["Identificar fases del ciclo de vida", "Fijar objetivos", "Soluciones técnicas", "Estrategias de mejora"], ans: 0 },
  { q: "Dato que permite medir el rendimiento respecto a una meta:", opts: ["Gestión ambiental", "Objetivo", "Indicador de desempeño", "Meta"], ans: 2 },
  { q: "Al fijar objetivos es importante partir de:", opts: ["Medios disponibles", "Análisis de cada proceso", "Selección de objetivos", "Horizonte temporal"], ans: 1 },
  { q: "Objetivo de la evaluación del desempeño medioambiental:", opts: ["Establecer fórmulas", "Lograr mejora continua", "Implantar indicadores", "Encontrar culpables"], ans: 1 },
  { q: "¿Objetivo principal de la evaluación del desempeño ambiental?", opts: ["Analizar impacto para mejora continua", "Marketing verde", "Obtener certificados", "Detección ineficiencias administrativas"], ans: 0 },
  { q: "¿Qué certificados ISO no requieren entidades externas?", opts: ["Tipo III", "Tipo II (autodeclaraciones)", "Tipo I", "No cubiertos por ISO"], ans: 1 },
  { q: "Un certificado de sostenibilidad es:", opts: ["Auditoría interna propia", "Prueba de cumplimiento de estándares", "Documento legal obligatorio general", "Informe financiero"], ans: 1 },
  { q: "Sobre la Etiqueta Ecológica Europea (EEE), señala la falsa:", opts: ["Requiere informe", "Pagar tasa", "Gestionado por la UE", "Es etiqueta tipo I"], ans: 2 },
  { q: "No se refiere a la inversión financiera:", opts: ["Producir un bien para venderlo", "Se refleja en títulos", "Rentabilidad, riesgo y liquidez", "Inversión productiva"], ans: 0 },
  { q: "Análisis de inversiones ISR valora:", opts: ["Riesgo", "Aspectos ASG", "Rentabilidad", "Todo lo anterior"], ans: 3 },
  { q: "Indicadores ISR con integración ASG:", opts: ["Empresas que cumplen criterios ASG", "Solo empresas de sostenibilidad", "Excluyen empresas incompatibles", "Consideran solo aspectos ASG"], ans: 0 },
  { q: "Estándar de información no financiera más antiguo:", opts: ["GRI", "Ley Info no Financiera", "CSRD", "NEIS"], ans: 0 },
  { q: "Sobre el estándar GRI, señala la falsa:", opts: ["Familia de estándares", "Usado por grandes empresas", "Primera versión año 2000", "Creado por la Unión Europea"], ans: 3 },
  { q: "El plan de sostenibilidad:", opts: ["Es obligatorio", "Actuaciones pasadas", "Guía acciones de la organización", "Corto plazo"], ans: 2 },
  { q: "El plan de sostenibilidad es herramienta de:", opts: ["Planificación", "Planificación y evaluación", "Planificación y comunicación", "Comunicación"], ans: 2 },
  { q: "Primer apartado de un plan de sostenibilidad:", opts: ["ODS clave", "Análisis del contexto", "Objetivos", "Impactos"], ans: 1 },
  { q: "El plan de sostenibilidad se caracteriza por ser:", opts: ["Auditoría externa", "Informe obligatorio general", "Solo de emisiones", "Planificación estratégica a medio/largo plazo"], ans: 3 },
  { q: "Para empresa agrícola, la sequía es un asunto con:", opts: ["Materialidad impacto", "Doble materialidad", "Sin materialidad", "Materialidad financiera"], ans: 3 },
  { q: "Prioridad nivel 1 en matriz de materialidad requiere:", opts: ["Elevada relevancia para grupos de interés", "Doble materialidad", "Relevancia y factibilidad", "Solo relevancia dirección"], ans: 0 },
  { q: "El informe o memoria de sostenibilidad:", opts: ["Informa desempeño", "Solo logros", "Periodo definido", "Herramienta comunicación políticas"], ans: 3 },
  { q: "En evaluación de impacto ambiental NO interviene:", opts: ["Informe medioambiental", "Promotor de obra", "Autoridad medioambiental", "Estudio impacto"], ans: 0 },
  { q: "La declaración de impacto ambiental la redacta:", opts: ["Oficina prensa", "Autoridad medioambiental", "Promotora", "Constructora"], ans: 1 },
  { q: "Blockchain para rastrear condiciones laborales afecta principalmente a:", opts: ["Financiero", "Ambiental", "Gobernanza", "Social"], ans: 2 },
  { q: "Sustituir diésel por vehículos eléctricos mejora principalmente:", opts: ["Financiero", "Gobernanza", "Ambiental", "Social"], ans: 2 },
  { q: "Programa de seguridad y bienestar para conductores mejora principalmente:", opts: ["Gobernanza", "Ambiental", "Social", "Financiero"], ans: 2 }
];